<?php
return array (
  'site_name' => 'Red Dog Cam Models',
  'broadcast_url' => 'https://chaturbate.com/broadcast/',
  'login_url' => 'https://chaturbate.com/auth/login/',
  'signup_url' => 'https://chaturbate.com/in/?track=default',
  'affiliate_id' => '',
  'google_analytics_id' => '',
  'privacy_email' => '',
  'primary_color' => '#8b0000',
  'footer_text' => '© 2026 Red Dog Cam Models.',
  'logo_path' => 'assets/logo.png',
  'favicon_path' => 'assets/favicon.ico',
  'whitelabel_domain' => 'chaturbate.com',
  'meta_home_title' => 'Red Dog Cam Models – Live Cam Discovery',
  'meta_home_desc' => 'Discover live adult cam models, categories, tags, and profiles.',
  'google_site_verification' => '',
  'bing_site_verification' => '',
  'llm_api_url' => 'https://api.openai.com/v1/chat/completions',
  'llm_model' => 'gpt-4o-mini',
  'site_base_url' => '',
  'meta_gender_titles' => array (
    'f' => 'Live Female Cams – Red Dog Cam Models',
    'm' => 'Live Male Cams – Red Dog Cam Models',
    't' => 'Live Trans Cams – Red Dog Cam Models',
    'c' => 'Live Couples Cams – Red Dog Cam Models',
  ),
  'meta_gender_descs' => array (
    'f' => 'Browse live female cam models.',
    'm' => 'Browse live male cam models.',
    't' => 'Browse live trans cam models.',
    'c' => 'Browse live couples cam models.',
  ),
  'cams_per_page' => 96,
  'admin_password_hash' => '$2y$12$x.WPiiR4hzRjWxtCQoxXnejkCn1AHP1XlCilQQ63tBaYGX8pg4sBm',
  'slugs' => array (
    'f' => 'girls',
    'm' => 'guys',
    't' => 'trans',
    'c' => 'couples',
    'model' => 'model',
  ),
  'llm_provider' => 'openai',
  'llm_api_key' => getenv('OPENAI_API_KEY') ?: '',
  'llm_rewrite_all_bios' => '0',
  'llm_rewrite_mode' => 'missing',
  'llm_stale_days' => 7,
  'llm_manual_ids' => '',
);
